FROM python:3.12

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY .env .

ENV API_ID=$API_ID
ENV API_HASH=$API_HASH
ENV BOT_TOKEN=$BOT_TOKEN
ENV SUBSCRIPTION_KEY1=$SUBSCRIPTION_KEY1
ENV SUBSCRIPTION_KEY2=$SUBSCRIPTION_KEY2
ENV ENDPOINT=$ENDPOINT
ENV CUSTOM_CONFIG_ID=$CUSTOM_CONFIG_ID

CMD ["python", "main.py"]
